### ISSUE TITLE
Uncaught TypeError: this.action.disposalAction is not a function

### ISSUE THREAD

**Issue by ghost** [awaw00/autoclose#33]
TypeError: this.action.disposalAction is not a function
    at Object._paneItemChanged (file:///C:/Users/nagen/.atom/packages/autoclose/lib/autoclose.coffee:39:29)
    at file:///C:/Users/nagen/.atom/packages/autoclose/lib/autoclose.coffee:26:8
    at Function.simpleDispatch (C:\Users\nagen\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:1214120)
    at Emitter.emit (C:\Users\nagen\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:1215561)
    at Workspace.didActivatePaneContainer (C:\Users\nagen\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:424255)
    at Dock.subscriptions.l.paneContainer.onDidActivatePane (C:\Users\nagen\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:469080)
    at Function.simpleDispatch (C:\Users\nagen\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:1214120)
    at Emitter.emit (C:\Users\nagen\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:1215561)
    at PaneContainer.didActivatePane (C:\Users\nagen\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:446491)
    at Pane.activate (C:\Users\nagen\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:463814)
    at Pane.focus (C:\Users\nagen\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:455257)
    at HTMLElement.handleFocus (C:\Users\nagen\AppData\Local\atom\app-1.45.0\resources\app.asar\src\pane-element.js:41:20)

**Comment by ghost** [comment]
how to remove that]

**Comment by ghost** [comment]
I have uninstalled and installed it again @swethasrinivasan166

**Comment by Rknitp** [comment]
just close the atom and again open it. My issue got resolved by this.

**Comment by GMHANSEN89** [comment]
I've uninstalled and reinstalled, closed and re-opened Atom, and I'm still getting the error. Any further thoughts out there?

**Comment by WoaWoa2** [comment]
does this error effect the repository too?
